### ISSUE TITLE
Even if players don't answer the ChoiceManager in time, they are still taken to the next page without having selected any options

### ISSUE THREAD

**Issue by lieuzhenghong** [lieuzhenghong/bee-experiment#4]
In my game, I have the following stages:

```javascript
     stager
        .next('instructions')
        .next('quiz')
        .next('communicate')
	.step('send')
	.step('receive')
	.next('game')
	.next('results')
        .next('end')
```

In several of these steps, I require players to have filled in options, be it a comprehension quiz, or choosing what message to send to another player, or picking the actual option in a game.

In `game.settings.js` I have the following timer settings:

```javascript
     */
    TIMER: {
        instructions: 10000,
		quiz: 120000,
		send: 120000,
		receive: 20000,
		game: 120000,
		results: 20000
    },
```

I do not include PushClients.

But when the time runs out, all players are pulled to the next step even if they haven't filled in all the questions in the ChoiceManager. This may be intended behaviour, but it's quite unwanted. I would like to disconnect a player if they don't manage to answer the questions/choose a message/select a decision in time. Would appreciate advice on what to do here.

**Comment by lieuzhenghong** [comment]
Dear @shakty, I'd appreciate your help here very much.

**Comment by shakty** [comment]
Hi zhenghong,

Yes, that it is the default behavior, it's useful to keep games with many players flowing. pushClients is also not going to help you with this. So, I think that the only solution for now is to include a custom script in the logic. Please try the following and let me know if it works.

In logic, you can overwrite the timer property in the desired step. Make it 10 seconds longer than in player. Inside the cb property of the step, you can start a timer expiring 5 seconds after the player. There you check who is DONE who is not, and you can disconnect those who are not done.

```javascript
node.game.pl.each(function(p) {
   if (p.stageLevels !==  node.constants.stageLevels.DONE) {
       node.disconnectClient(p);
       // Notice that the disconnection will trigger the disconnection handler.
   }
});
```

**Comment by lieuzhenghong** [comment]
Ah, I get what you mean. Just one question, though --- how do I overwrite the timer property in `logic.js`? `node.game.settings.TIMER.<stepname>`?

```javascript
	stager.extendStep('quiz', {
        cb: function() {

			// [TODO] override time

			setTimeOut(function () {
				node.game.pl.each(function(p) {
				   if (p.stageLevels !==  node.constants.stageLevels.DONE) {
					   node.disconnectClient(p);
					   // Notice that the disconnection will trigger the disconnection handler.
				   }
				});
			}, settings.TIMER.quiz + 5000)
        }
    });


```

**Comment by shakty** [comment]
just add a timer property to the extendStep object

**Comment by lieuzhenghong** [comment]
In `logic.js`:

```javascript
	stager.extendStep('quiz', {
		timer: 30000,

        cb: function() {
			setTimeout(function () {
				console.log("setTimeout function called")
				node.game.pl.each(function(p) {
				   if (p.stageLevels !==  node.constants.stageLevels.DONE) {
					   node.disconnectClient(p);
					   // Notice that the disconnection will trigger the disconnection handler.
				   }
				});
			}, 25000)
        }

    });
```

What I observe:

- Timer doesn't seem to be overridden (no change on the VisualTimer)
- Both players seem to be disconnected even though one of them has clicked Done already:

```
setTimeout function called
Disconnection: 618737661280537 (server stage: 2.1.1)
Disconnection: 47123914420837 (server stage: 2.1.1)
```

Upon the timer running out, both players go to a "Resuming soon..." overlay

![image](https://user-images.githubusercontent.com/7903071/71975198-45511100-324e-11ea-9729-b620a66987ba.png)

**Comment by lieuzhenghong** [comment]
Also, the setTimeout function you gave still triggers even after that particular step. See the following console output, where the setTimeout function triggers in the receive stage (one stage after the quiz stage)

```
Message string: I intend to choose B. You should choose B. 
setTimeout function called
Disconnection: 672632663386567 (server stage: 3.2.1)
Disconnection: 705270154272283 (server stage: 3.2.1)
```

I'll have to find some way to remove the setTimeout callbacks after every step.

**Comment by shakty** [comment]
The visual timer is not supposed to change, that is the timer for the player. You just want the logic to take actions after that timer expires. You are right, we forgot to remove the timeout. You need to save it under node.game.mytimeout, and you can destroy it in the exit function of the step.

exit: function() {
    clearTimeout(node.game.mytimeout);
})l

**Comment by lieuzhenghong** [comment]
Do you know why both players get disconnected? I'm pushing now

**Comment by lieuzhenghong** [comment]
Also how do I prevent the players from being stuck at "Resuming soon" forever?

**Comment by shakty** [comment]
Can you please update your repo in a way that it contains only your game folder? It makes my life easier to check your progress.

**Comment by lieuzhenghong** [comment]
I have done so in this repo: [https://github.com/lieuzhenghong/communication-game](https://github.com/lieuzhenghong/communication-game)

**Comment by shakty** [comment]
Sorry for the delay. I checked your code and indeed was creating troubles, so I came up with another approach.


On player, add a timeup handler to force disconnection:
```js
        timeup: function() {
            node.socket.disconnect();
        }
```
On player, I would also add the disconnection box in the init function:
```js
        this.discBox = node.widgets.append('DisconnectBox', header, {
            showStatus: true
        });
```
On logic, set the disconnection handler for all stages that needs it.
```js
    stager.setDefaultProperty('minPlayers', [
        2, function() {
            node.game.gotoStep('end');
        }
    ]);

    stager.extendStep('end', {
        minPlayers: null,
        ...
    });
```
In settings reduce the waiting time for reconnection:
```js
    WAIT_TIME: 5
```
It should work now.

**Comment by lieuzhenghong** [comment]
Dear Stefano, thanks so much for the reply. I'm still a bit lost about what the idea is, though. I've done the changes to logic and in settings, but I'm not sure what the idea of the code is. Is anything calling the `timeup` function in `player.js`? What should be calling it? What about `WAIT_TIME`?

In any case, I've pushed the changes and I'd like to move discussion to lieuzhenghong/communication-game#1, if possible.
